# Generated by Django 4.1.1 on 2022-09-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_news_options_alter_news_avtor_alter_news_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='sop',
            field=models.CharField(choices=[('s', 'small'), ('v', 'vertall'), ('h', 'humall')], default='s', max_length=2),
        ),
        migrations.AddField(
            model_name='news',
            name='views',
            field=models.IntegerField(default=1, verbose_name='prosmotr'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=40, unique=True, verbose_name='статия аты: '),
        ),
    ]
