# Generated by Django 4.1.1 on 2022-09-11 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_news_sop_news_views_alter_news_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='sop',
        ),
    ]
