# Generated by Django 4.1.1 on 2022-10-05 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_remove_news_sop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_link', models.URLField(max_length=250, verbose_name='Длинная ссылка')),
                ('short_link', models.CharField(max_length=250, unique=True, verbose_name='Сокращенная ссылка')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sslka',
                'verbose_name_plural': 'sslka',
            },
        ),
        migrations.DeleteModel(
            name='news',
        ),
    ]
